[package]
name = "bait"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.0"
tokio = { version = "1.10.0", features = ["full"] }
lazy_static = "1.4.0"
reqwest = "0.12.2"
actix-rt = "2.6.0"
serde_json = "1.0.70"
[dev-dependencies]
wiremock = "0.6.0"
